"""Write readiness / topology / failover results to reports/ (JSON + HTML)."""

from __future__ import annotations

import html
import json
from datetime import datetime, timezone
from pathlib import Path

REPORTS_DIR = Path(__file__).resolve().parent.parent / "reports"

_STATUS_COLOR = {"PASS": "#1a7f37", "WARN": "#9a6700", "FAIL": "#cf222e"}


def _write(name: str, payload: dict) -> Path:
    REPORTS_DIR.mkdir(exist_ok=True)
    payload = {"generated_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
               **payload}
    path = REPORTS_DIR / name
    path.write_text(json.dumps(payload, indent=2, default=str))
    return path


def write_readiness(report: dict, scenario: str) -> Path:
    return _write("dr_readiness.json", {"scenario": scenario, **report})


def write_topology(topo: dict) -> Path:
    return _write("topology.json", topo)


def write_failover(result: dict) -> Path:
    return _write("dr_failover.json", result)


def render_html_report(report: dict, target: str, controllers: dict | None = None) -> str:
    """Self-contained HTML for a scheduled DR-readiness report / email body."""
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    oc = _STATUS_COLOR.get(report["overall"], "#57606a")
    cnt = report["counts"]

    rows = []
    for c in report["checks"]:
        col = _STATUS_COLOR.get(c["status"], "#57606a")
        ev = "<br>".join(html.escape(e) for e in c["evidence"])
        fix = (f'<div style="color:#0969da;margin-top:4px">&#9656; {html.escape(c["remediation"])}</div>'
               if c["status"] != "PASS" and c["remediation"] else "")
        rows.append(f"""
          <tr>
            <td style="padding:8px;border-bottom:1px solid #d0d7de;white-space:nowrap">
              <b style="color:{col}">{c['status']}</b></td>
            <td style="padding:8px;border-bottom:1px solid #d0d7de">
              <b>{html.escape(c['title'])}</b>
              <div style="color:#57606a">{html.escape(c['detail'])}</div>
              <div style="color:#8c959f;font:12px/1.5 monospace;margin-top:4px">{ev}</div>
              {fix}
            </td>
          </tr>""")

    ctrl_lines = ""
    if controllers:
        for name, cd in controllers.items():
            state = "reachable" if getattr(cd, "reachable", False) else "UNREACHABLE"
            ctrl_lines += f"<li>{html.escape(name)} ({html.escape(str(cd.mgmt_ip))}) &mdash; {state}</li>"

    return f"""<!doctype html><html><body style="font:14px/1.6 -apple-system,Segoe UI,Arial,sans-serif;color:#1f2328;max-width:820px;margin:0 auto;padding:20px">
      <h2 style="margin:0">Catalyst 9800 Wireless DR Readiness</h2>
      <div style="color:#57606a">target: <b>{html.escape(target)}</b> &nbsp;·&nbsp; {ts}</div>
      <p style="font-size:18px;margin:16px 0">
        Overall: <b style="color:{oc}">{report['overall']}</b>
        &nbsp; Score: <b>{report['score']}%</b>
        &nbsp; <span style="color:#57606a">PASS {cnt['pass']} / WARN {cnt['warn']} / FAIL {cnt['fail']}</span>
      </p>
      {"<ul>" + ctrl_lines + "</ul>" if ctrl_lines else ""}
      <table style="border-collapse:collapse;width:100%">{''.join(rows)}</table>
      <p style="color:#8c959f;font-size:12px;margin-top:20px">
        Generated by catalyst9800-dr-readiness. Read-only: only "show" commands were issued.</p>
    </body></html>"""


def write_html_report(report: dict, target: str, controllers: dict | None = None) -> Path:
    REPORTS_DIR.mkdir(exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    path = REPORTS_DIR / f"dr_readiness_{target}_{stamp}.html"
    path.write_text(render_html_report(report, target, controllers))
    (REPORTS_DIR / "dr_readiness_latest.html").write_text(path.read_text())
    return path
